"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"\t<meta charset=\"utf-8\">\n"
"\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
"\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.2/darkly/bootstrap.min.css\" integrity=\"sha512-8lE+UgnY2CgbE+WDsGwSwAiMOswuRYm11jXYV5KWH6XfSDAzrdRMbPQDpCwzVjJbe9quHrNNPV6N/llRKnw5Hg==\" crossorigin=\"anonymous\" />\n"
"\t<title>Sidekick64 Tuning</title>\n"
"</head>\n"
"<body>\n"
"\t&nbsp;<br/><div class=\"container\">\t\n"
"\t<h3>Sidekick64 Tuning</h3>\n"
"\t<div class=\"container bg-dark\">\n"
"\n"
"\t\t<form action=\"tuning.html\" method=\"post\" enctype=\"application/x-www-form-urlencoded\">\n"
"\t\t<table>\n"
"\t\t\t%s\n"
"\t\t</table>\n"
"\t\t<p><input type=\"submit\" value=\"Submit\" /></p>\n"
"\t\t</form>\n"
"\n"
"\t</div>\n"
"\t<p class=\"small\"><a href=\"https://github.com/frntc/Sidekick64\" target=\"_blank\">Sidekick64</a></p>\n"
"\t<p class=\"small\">Based on the <a href=\"https://github.com/rsta2/circle\" target=\"_blank\">Circle</a> C++ bare metal environment.</p>\n"
"\t<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\n"
"\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\n"
"\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\t\n"
"</div>\n"
"</body>\n"
"</html>\n"
""