"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"\t<meta charset=\"utf-8\">\n"
"\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
"\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.2/darkly/bootstrap.min.css\" integrity=\"sha512-8lE+UgnY2CgbE+WDsGwSwAiMOswuRYm11jXYV5KWH6XfSDAzrdRMbPQDpCwzVjJbe9quHrNNPV6N/llRKnw5Hg==\" crossorigin=\"anonymous\" />\n"
"\t<title>Sidekick64 Webserver</title>\n"
"</head>\n"
"<body>\n"
"\t&nbsp;<br/><div class=\"container\">\t\n"
"\t<h3>Sidekick64 Webserver</h3>\n"
"\t<div class=\"container bg-dark\">\n"
"\n"
"\t\t<p>%s</p>\n"
"\n"
"\t\t<form action=\"index.html\" method=\"post\" enctype=\"multipart/form-data\">\n"
"\t\t\t<div class=\"form-group\">\n"
"\t\t\t\t\n"
"\t\t\t\t<div class=\"custom-file\">\n"
"\t\t\t\t  <input type=\"file\" class=\"custom-file-input\" id=\"customFile\">\n"
"\t\t\t\t  <label class=\"custom-file-label\" for=\"customFile\">Kernel image file (kernel*.img)</label>\n"
"\t\t\t\t</div>\n"
"\t\t\t\t\n"
"\t\t\t\t<input type=\"submit\" class=\"btn btn-success\" value=\"Upload and reboot\" />\n"
"\t\t\t</div>\n"
"\t\t</form>\n"
"\n"
"\t</div>\n"
"\t<p class=\"small\"><a href=\"https://github.com/frntc/Sidekick64\" target=\"_blank\">Sidekick64</a></p>\n"
"\t<p class=\"small\">Based on the <a href=\"https://github.com/rsta2/circle\" target=\"_blank\">Circle</a> C++ bare metal environment. Circle %s</a> running on %s</p>\n"
"\t<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\n"
"\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\n"
"\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\t\n"
"\t</div>\n"
"</body>\n"
"</html>\n"
""