"<!doctype html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"\t<meta charset=\"utf-8\">\n"
"\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
"\t<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" integrity=\"sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z\" crossorigin=\"anonymous\">\n"
"\t<title>Sidekick64 Webserver</title>\n"
"</head>\n"
"<body>\n"
"\t<h1>Sidekick64 Webserver</h1>\n"
"\n"
"\t\t<p>%s</p>\n"
"\n"
"\t\t<form action=\"index.html\" method=\"post\" enctype=\"multipart/form-data\">\n"
"\t\t\t<table>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<th>Kernel image file (kernel*.img)</th>\n"
"\t\t\t</tr>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><input type=\"file\" name=\"kernelimg\" /></td>\n"
"\t\t\t</tr>\n"
"\t\t\t<tr>\n"
"\t\t\t\t<td><input type=\"submit\" value=\"Boot now!\" /></td>\n"
"\t\t\t</tr>\n"
"\t\t\t</table>\n"
"\t\t</form>\n"
"\n"
"\t<hr />\n"
"\t<p class=\"small\"><a href=\"https://github.com/frntc/Sidekick64\" target=\"_blank\">Sidekick64</a></p>\n"
"\t<p class=\"small\">Based on the <a href=\"https://github.com/rsta2/circle\" target=\"_blank\">Circle</a> C++ bare metal environment.</p>\n"
"\t<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\n"
"\t<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\n"
"\t<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\" integrity=\"sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV\" crossorigin=\"anonymous\"></script>\t\n"
"</body>\n"
"</html>\n"
""