#
# Makefile
#

CONTENT	= index.h style.h ledoff.h ledon.h favicon.h

EXTRACLEAN = $(CONTENT) converttool

%.h: %.html
	@echo "  GEN   $@"
	@./converttool $< > $@

%.h: %.css
	@echo "  GEN   $@"
	@./converttool $< > $@

%.h: %.png
	@echo "  GEN   $@"
	@./converttool -b $< > $@
	
%.h: %.ico
	@echo "  GEN   $@"
	@./converttool -b $< > $@
	
$(CONTENT): converttool

converttool: converttool.c
	@echo "  TOOL  $@"
	@gcc -o converttool converttool.c
